#!/usr/bin/env python3
"""
MP3 to Arduino Melody Converter

This script analyzes an MP3 file and converts it to a simple melody
that can be played on Arduino using the tone() function.

Requirements:
- pip install librosa numpy

Usage:
python mp3_to_melody_converter.py sample.mp3
"""

import sys
import os
import librosa
import argparse


# Arduino note frequencies (in Hz)
ARDUINO_NOTES = {
    'C4': 262, 'D4': 294, 'E4': 330, 'F4': 349, 'G4': 392, 'A4': 440,
    'B4': 494, 'C5': 523, 'D5': 587, 'E5': 659, 'F5': 698, 'G5': 784,
    'A5': 880, 'B5': 988, 'C6': 1047, 'D6': 1175, 'E6': 1319, 'F6': 1397,
    'G6': 1568, 'A6': 1760, 'B6': 1976
}

# Timing constants (in milliseconds)
QUARTER_NOTE = 500
HALF_NOTE = 1000
WHOLE_NOTE = 2000
EIGHTH_NOTE = 250


def find_closest_note(frequency):
    """Find the closest Arduino note frequency to the given frequency."""
    if frequency <= 0:
        return 0  # Rest/silence

    # Find the closest note
    closest_note = 0
    min_diff = float('inf')

    for note_name, note_freq in ARDUINO_NOTES.items():
        diff = abs(frequency - note_freq)
        if diff < min_diff:
            min_diff = diff
            closest_note = note_freq

    return closest_note


def extract_melody_from_mp3(mp3_path, max_notes=50):
    """
    Extract a simple melody from an MP3 file.

    Args:
        mp3_path: Path to the MP3 file
        max_notes: Maximum number of notes to extract

    Returns:
        List of (frequency, duration) tuples
    """
    try:
        print(f"Loading MP3 file: {mp3_path}")

        # Load the audio file
        y, sr = librosa.load(mp3_path, sr=None, duration=30)  # Limit to 30s

        # Extract pitch (fundamental frequency)
        pitches, magnitudes = librosa.piptrack(y=y, sr=sr)

        # Get the dominant pitch at each time frame
        pitch_times = []
        for t in range(pitches.shape[1]):
            index = magnitudes[:, t].argmax()
            pitch = pitches[index, t]
            if pitch > 0:  # Valid pitch
                time_val = (t * librosa.get_duration(y=y, sr=sr) /
                            pitches.shape[1])
                pitch_times.append((time_val, pitch))

        # Sample evenly spaced notes
        if len(pitch_times) > max_notes:
            step = len(pitch_times) // max_notes
            pitch_times = pitch_times[::step][:max_notes]

        # Convert to Arduino melody format
        melody = []
        for i, (time, pitch) in enumerate(pitch_times):
            frequency = find_closest_note(pitch)
            duration = QUARTER_NOTE  # Default duration

            # Vary duration based on magnitude
            if i < len(pitch_times) - 1:
                time_diff = pitch_times[i + 1][0] - time
                if time_diff > 0.5:
                    duration = HALF_NOTE
                elif time_diff < 0.2:
                    duration = EIGHTH_NOTE

            melody.append((frequency, duration))

        return melody

    except Exception as e:
        print(f"Error processing MP3: {e}")
        return []


def generate_arduino_code(melody, output_file=None):
    """
    Generate Arduino code from the melody.

    Args:
        melody: List of (frequency, duration) tuples
        output_file: Optional output file path
    """
    if not melody:
        print("No melody to convert!")
        return

    # Generate the melody array
    melody_code = "int sampleMelody[][2] = {\n"
    for freq, duration in melody:
        melody_code += f"  {{{freq}, {duration}}},\n"
    melody_code += "};"

    # Generate complete Arduino code
    arduino_code = f"""/*
 * Auto-generated melody from MP3 file
 * Generated by mp3_to_melody_converter.py
 */

const int BUZZER_PIN = 8;

// Musical note frequencies (in Hz)
const int NOTE_C4 = 262;
const int NOTE_D4 = 294;
const int NOTE_E4 = 330;
const int NOTE_F4 = 349;
const int NOTE_G4 = 392;
const int NOTE_A4 = 440;
const int NOTE_B4 = 494;
const int NOTE_C5 = 523;
const int NOTE_D5 = 587;
const int NOTE_E5 = 659;
const int NOTE_F5 = 698;
const int NOTE_G5 = 784;
const int NOTE_A5 = 880;
const int NOTE_B5 = 988;

// Timing definitions
const int QUARTER_NOTE = 500;
const int HALF_NOTE = 1000;
const int WHOLE_NOTE = 2000;
const int EIGHTH_NOTE = 250;

// Extracted melody from MP3
{melody_code}

void setup() {{
  pinMode(BUZZER_PIN, OUTPUT);
  Serial.begin(9600);
  Serial.println("Playing MP3 melody...");
}}

void loop() {{
  playMelody(sampleMelody, sizeof(sampleMelody) / sizeof(sampleMelody[0]));
  Serial.println("Melody finished. Playing again in 2 seconds...");
  delay(2000);
}}

void playMelody(int melody[][2], int length) {{
  for (int i = 0; i < length; i++) {{
    int frequency = melody[i][0];
    int duration = melody[i][1];

    if (frequency > 0) {{
      Serial.print("Playing note: ");
      Serial.print(frequency);
      Serial.print(" Hz for ");
      Serial.print(duration);
      Serial.println(" ms");

      tone(BUZZER_PIN, frequency, duration);
      delay(duration + 50);
      noTone(BUZZER_PIN);
    }} else {{
      // Rest (silence)
      delay(duration);
    }}
  }}
}}
"""

    if output_file:
        with open(output_file, 'w') as f:
            f.write(arduino_code)
        print(f"Arduino code saved to: {output_file}")
    else:
        print("\n" + "="*50)
        print("GENERATED ARDUINO CODE:")
        print("="*50)
        print(arduino_code)


def main():
    parser = argparse.ArgumentParser(
        description='Convert MP3 to Arduino melody')
    parser.add_argument('mp3_file', help='Path to the MP3 file')
    parser.add_argument('--output', '-o', help='Output Arduino file path')
    parser.add_argument('--max-notes', '-n', type=int, default=50,
                        help='Maximum number of notes to extract (default: 50)')

    args = parser.parse_args()

    if not os.path.exists(args.mp3_file):
        print(f"Error: File {args.mp3_file} not found!")
        sys.exit(1)

    print("=== MP3 to Arduino Melody Converter ===")
    print(f"Processing: {args.mp3_file}")
    print(f"Max notes: {args.max_notes}")

    # Extract melody from MP3
    melody = extract_melody_from_mp3(args.mp3_file, args.max_notes)

    if melody:
        print(f"\nExtracted {len(melody)} notes from MP3")
        print("\nMelody preview (first 10 notes):")
        for i, (freq, duration) in enumerate(melody[:10]):
            note_name = "REST" if freq == 0 else f"{freq}Hz"
            print(f"  {i+1:2d}. {note_name:>6} for {duration}ms")

        # Generate Arduino code
        output_file = args.output or "mp3_melody.ino"
        generate_arduino_code(melody, output_file)

        print(f"\n✅ Success! Upload the generated code to your Arduino.")
        print(f"   Connect buzzer to pin 8 and GND.")

    else:
        print("❌ Failed to extract melody from MP3 file.")
        print("   Make sure the file is a valid MP3 with clear audio.")


if __name__ == "__main__":
    main()
