/*
 * Auto-generated melody from MP3 file
 * Generated by mp3_to_melody_converter.py
 */

const int BUZZER_PIN = 8;

// Musical note frequencies (in Hz)
const int NOTE_C4 = 262;
const int NOTE_D4 = 294;
const int NOTE_E4 = 330;
const int NOTE_F4 = 349;
const int NOTE_G4 = 392;
const int NOTE_A4 = 440;
const int NOTE_B4 = 494;
const int NOTE_C5 = 523;
const int NOTE_D5 = 587;
const int NOTE_E5 = 659;
const int NOTE_F5 = 698;
const int NOTE_G5 = 784;
const int NOTE_A5 = 880;
const int NOTE_B5 = 988;

// Timing definitions
const int QUARTER_NOTE = 500;
const int HALF_NOTE = 1000;
const int WHOLE_NOTE = 2000;
const int EIGHTH_NOTE = 250;

// Extracted melody from MP3
int sampleMelody[][2] = {
  {262, 1000},
  {659, 1000},
  {349, 1000},
  {587, 1000},
  {698, 1000},
  {587, 1000},
  {349, 1000},
  {659, 1000},
  {262, 1000},
  {262, 1000},
  {494, 1000},
  {494, 1000},
  {262, 1000},
  {494, 1000},
  {392, 1000},
  {392, 1000},
  {262, 1000},
  {523, 1000},
  {523, 1000},
  {494, 500},
};

void setup() {
  pinMode(BUZZER_PIN, OUTPUT);
  Serial.begin(9600);
  Serial.println("Playing MP3 melody...");
}

void loop() {
  playMelody(sampleMelody, sizeof(sampleMelody) / sizeof(sampleMelody[0]));
  Serial.println("Melody finished. Playing again in 2 seconds...");
  delay(2000);
}

void playMelody(int melody[][2], int length) {
  for (int i = 0; i < length; i++) {
    int frequency = melody[i][0];
    int duration = melody[i][1];
    
    if (frequency > 0) {
      Serial.print("Playing note: ");
      Serial.print(frequency);
      Serial.print(" Hz for ");
      Serial.print(duration);
      Serial.println(" ms");
      
      tone(BUZZER_PIN, frequency, duration);
      delay(duration + 50);
      noTone(BUZZER_PIN);
    } else {
      // Rest (silence)
      delay(duration);
    }
  }
}
